version: 4.0.{build}
image: Visual Studio 2017
configuration: Release
build_script:
- ps: dotnet build -c Release
test_script:
- ps: >-
    cd nClam.Tests
    dotnet test
artifacts:
- path: nClam\bin\Release\*.nupkg